name: GoVulnCheck

on:
  push:
    branches: ["main"]
    # run only against tags
    tags:
      - "*"
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - id: govulncheck
        uses: golang/govulncheck-action@v1