name: Integration Test MySQL (testcontainers-go)

on:
  push:
    # run only against tags
    tags:
      - "*"
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - name: setup atlas
        uses: ariga/setup-atlas@v0
      - name: Build
        run: go build -v ./...
      - name: Run integration tests
        run: TESTCONTAINERS_RYUK_DISABLED=true go test ./...